config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#index'

  namespace :api, defaults: { format: :json } do
    resources :photos, only: [:create, :destroy, :index, :show, :update]
    resources :albums, only: [:create, :destroy, :index, :show, :update]
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id          :integer          not null, primary key
#  author_id   :integer          not null
#  title       :string           not null
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Album < ActiveRecord::Base
  validates :author_id, :title, presence: true

  belongs_to :user,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id

  has_many :photos,
    class_name: "Photo",
    foreign_key: :album_id,
    primary_key: :id
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :string
#  image_url   :string           not null
#  author_id   :integer          not null
#  album_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  medium      :string           not null
#  surface     :string           not null
#

class Photo < ActiveRecord::Base
  MEDIA = ['oil', 'acrylic', 'watercolor', 'gouache']
  SURFACES = ['canvas', 'paper', 'wood', 'metal', 'marble']

  validates :medium, inclusion: { in: MEDIA }
  validates :surface, inclusion: { in: SURFACES }

  belongs_to :user,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id

  belongs_to :album,
    class_name: "Album",
    foreign_key: :album_id,
    primary_key: :id
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :password_digest, :username, :session_token,
    presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true}

  has_many :user_images,
    dependent: :destroy

  has_many :photos,
    class_name: "Photo",
    foreign_key: :author_id,
    primary_key: :id,
    dependent: :destroy

  has_many :albums,
    class_name: "Album",
    foreign_key: :author_id,
    primary_key: :id,
    dependent: :destroy

  attr_reader :password

  after_initialize :ensure_session_token

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    user if user && user.is_password?(password)
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    save!
    self.session_token
  end
end

app/models/user_image.rb
# == Schema Information
#
# Table name: user_images
#
#  id          :integer          not null, primary key
#  user_id     :integer          not null
#  cover_url   :string           not null
#  profile_url :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class UserImage < ActiveRecord::Base
  belongs_to :user
end

app/controllers/api/albums_controller.rb
class Api::AlbumsController < ApplicationController
  def create
    @album = Album.new(album_params)
    @album.author_id = current_user.id

    if @album.save
      render :show
    else
      render json: @album.errors.full_messages, status: 422
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    render :show
  end

  def index
    @albums = Album.includes(:photos).where(
      author_id: current_user.id
    )
  end

  def show
    @album = Album.includes(:photos).find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    @album.update(album_params)

    render :show
  end

  private
  def album_params
    params.require(:album).permit(
      :title, :description, :author_id
    )
  end
end

app/controllers/api/photos_controller.rb
class Api::PhotosController < ApplicationController
  def create
    @photo = Photo.new(photo_params)
    @photo.author_id = current_user.id
    # @photo.image_url = Cloudinary::Uploader.upload(@photo.image_url)["secure_url"]

    if @photo.save
      render :show
    else
      render json: @photo.errors.full_messages, status: 422
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    render :show
  end

  def index
    @photos = Photo.where(
      author_id: current_user.id
    )
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    @photo.update(photo_params)
    render :show
  end

  private
  def photo_params
    params.require(:photo).permit(
      :title, :description, :image_url, :medium, :surface, :author_id, :album_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :require_logged_in, :signed_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def log_in!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def log_out
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end

  def require_logged_in
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user
      log_in!(user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Bad username / password combo"]
      render :new
    end
  end

  def destroy
    log_out
    render json: {}
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :index, :require_logged_in

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in!(@user)
      redirect_to root_url
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/api/albums_helper.rb
module Api::AlbumsHelper
end

app/helpers/api/photos_helper.rb
module Api::PhotosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    html = <<-HTML
      <input type="hidden"
             name="authenticity_token"
             value="#{form_authenticity_token}">
    HTML
    html.html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>Paintr</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%paintings=%w(starry_night artist-facing-blank-canvas autumn_landscape
      boat-sea-landscape Creation_of_Adam Eckenbrecher Freedom_from_want
      jeff-watts1 jeff-watts2 landscape landscape2 landscape3
      marshes-painting melting-clocks modern-art Mona_Lisa
      painting-background painting-background2 paintings_fences
      picasso school-of-athens Summer-Days water-color) %>
<% painting = paintings.sample %>
<div class="transparent-div <%= painting %>"></div>

<% if current_user  %>
<script>
  window.CURRENT_USER_ID = <%= current_user.id %>
  window.CURRENT_USERNAME = "<%= current_user.username %>"
</script>
<% end %>

<%= flash[:errors] %>

<%= yield %>

</body>
</html>

app/views/static_pages/index.html.erb
<div id='content'>
</div>

app/views/users/new.html.erb
<div class="paintr-title">
  <h1>Welcome to Paintr!</h1>
  <h3>It's where to share your paintings.</h3>
</div>

<div class="jumbotron col-xs-offset-4 col-xs-4">

  <h2>Sign Up</h2>

  <form class="form-group" action="<%= users_url %>" method="post">

    <%= auth_token %>

    <input placeholder="username" class="form-control" id ="user_username" type="text" name="user[username]" value="<%=@user.username %>">
  <br/>
  <br/>
    <input placeholder="password" class="form-control" id="user_password" type="password" name="user[password]">
  <br/>
  <br/>
    <input class="form-control btn btn-primary" type="submit" value="Sign Up">
  </form>

  <br/>

  <p>Already have an account? <%= link_to "Sign in", new_session_url %>.</p>
  <p>Or try a <a id="demo-link">demo account</a>.</p>
  </div>

  <script type=text/javascript>
    $(function(){
      $('#demo-link').on('click', function() {
        $('input:text').val('vincent');
        $('input:password').val('password');
        $.ajax({
          url: '/session',
          type: "POST",
          data: { user: {username: 'vincent', password: 'password'}  },
          success: function() {
            window.location.href = "/";
          }
        })
      });
    })
  </script>

</div>